### ISSUE TITLE
Adding a new section causes a part of the code of the first section to be overwritten.

### ISSUE THREAD

**Issue by hackerbytermux** [M3str3/HexSpell#4]
adding a new section causes a part of the code of the first section to be overwritten, which causes an error when trying to run the program after the changes

![photo_2024-09-19_02-35-46](https://github.com/user-attachments/assets/7711ca38-a85c-4b9a-80f1-4a4d678841c8)
![photo_2024-09-19_02-35-22](https://github.com/user-attachments/assets/49020b92-bbe9-4e34-9e70-860fe1ce06bc)

**Comment by M3str3** [comment]
Hi man, first of all thanks for posting the error!!!! I've been trying to replicate it without much success, I've changed the test binary and in fact it has helped me to discover another issue (#5 ).

But in none of the tests I have lost information from the first section. Can you share the binary? or the code? thanks!

**Comment by hackerbytermux** [comment]
Hi, thanks, here's the project and the files I used
[project-p.zip](https://github.com/user-attachments/files/17078940/project-p.zip)

**Comment by hackerbytermux** [comment]
i think we need to modify pointer_to_raw_data of all section and add the space between header and first section

**Comment by M3str3** [comment]
Hello again @hackerbytermux,

Thank you for your patience and for pointing out this issue. After testing, I can confirm that you were absolutely right!

## The error
![image](https://github.com/user-attachments/assets/f2074576-83bf-4c01-9393-02c7f3f25678)

The problem was indeed a collision when adding a new section header. I had not accounted for this case, as it hadn’t come up before. I’ve now implemented a fix that addresses this problem, and I will prepare it better tomorrow before pushing it to the `0.0.3` branch. By Monday, I plan to have this fix on the main branch and publish version `0.0.3` with the corrections. Thank you again for your valuable feedback!

![Pasted image 20240920214654](https://github.com/user-attachments/assets/f7daf8f3-6c93-4309-b647-9027b05de980)


## The Fix

The issue arises when the new section header overlaps with existing data. To resolve this, I’ve made the following adjustments in the `add_section()` function:

- **Collision check**: Before adding the new section, check if the new section header’s offset would collide with the `PointerToRawData` of the first section.
- **Buffer resizing**: If there’s a collision, we move all sections 40 bytes forward to create space for the new section header.
- **PointerToRawData update**: After moving the sections, we update the `PointerToRawData` of each section to reflect the new offsets.

### pe/mod.rs:add_section()

Here’s the updated code:

```rust
    /// Adds a section to the PE file.
    ///
    /// # Arguments
    /// * `new_section` - The new section header to be added.
    /// * `shellcode` - The shellcode or data to be added in the new section.
    ///
    /// # Returns
    /// A `Result` indicating success or failure of the operation.
    pub fn add_section(
        &mut self,
        new_section: section::PeSection,
        shellcode: Vec<u8>,
    ) -> Result<(), FileParseError> {
        const SECTION_HEADER_SIZE: usize = 40;

        // Check if new section header location collides with data in existing sections
        let first_section = self
            .sections
            .first()
            .ok_or(FileParseError::InvalidFileFormat)?;
        if new_section.name.offset + SECTION_HEADER_SIZE
            > first_section.pointer_to_raw_data.value as usize
        {
            // Collision detected, we need to move all sections 40 bytes forward

            let extra_space_needed = self.sections.len() * SECTION_HEADER_SIZE;
            let new_buffer_size = self.buffer.len() + extra_space_needed;

            // Resize the buffer to ensure sufficient space
            self.buffer.resize(new_buffer_size, 0);

            // Starting from the last section to avoid overwriting
            for section in self.sections.iter_mut().rev() {
                let raw_data_ptr = section.pointer_to_raw_data.value as usize;
                let raw_data_end = raw_data_ptr + section.size_of_raw_data.value as usize;

                if raw_data_end <= self.buffer.len() {
                    self.buffer.copy_within(
                        raw_data_ptr..raw_data_end,
                        raw_data_ptr + SECTION_HEADER_SIZE,
                    );
                }

                section.pointer_to_raw_data.update(
                    &mut self.buffer,
                    (section.pointer_to_raw_data.value + SECTION_HEADER_SIZE as u32),
                );
            }
        }

        let raw_data_ptr = new_section.pointer_to_raw_data.value;

        // Ensure the buffer is large enough to accommodate both the new section header and shellcode
        let new_total_buffer_size =
            raw_data_ptr as usize + new_section.size_of_raw_data.value as usize;
        if self.buffer.len() < new_total_buffer_size {
            self.buffer.resize(new_total_buffer_size, 0);
        }

        // Create the section header buffer to be inserted
        let mut section_header_buffer = Vec::with_capacity(SECTION_HEADER_SIZE);
        section_header_buffer.extend_from_slice(&new_section.name.value.as_bytes()[..8]);
        section_header_buffer.extend(&new_section.virtual_size.value.to_le_bytes());
        section_header_buffer.extend(&new_section.virtual_address.value.to_le_bytes());
        section_header_buffer.extend(&new_section.size_of_raw_data.value.to_le_bytes());
        section_header_buffer.extend(&new_section.pointer_to_raw_data.value.to_le_bytes());
        section_header_buffer.extend(&new_section.pointer_to_relocations.value.to_le_bytes());
        section_header_buffer.extend(&new_section.pointer_to_linenumbers.value.to_le_bytes());
        section_header_buffer.extend(&new_section.number_of_relocations.value.to_le_bytes());
        section_header_buffer.extend(&new_section.number_of_linenumbers.value.to_le_bytes());
        section_header_buffer.extend(&new_section.characteristics.value.to_le_bytes());

        // Ensure the section header buffer is exactly 40 bytes
        assert_eq!(section_header_buffer.len(), SECTION_HEADER_SIZE);

        // Insert the new section header
        self.buffer.splice(
            new_section.name.offset..new_section.name.offset + SECTION_HEADER_SIZE,
            section_header_buffer.iter().copied(),
        );

        // Inject the new code
        self.buffer.splice(
            raw_data_ptr as usize..raw_data_ptr as usize + shellcode.len(),
            shellcode.iter().copied(),
        );

        // Update headers
        self.header.size_of_image.update(
            &mut self.buffer,
            new_section.virtual_address.value + new_section.virtual_size.value,
        );
        self.header
            .number_of_sections
            .update(&mut self.buffer, self.header.number_of_sections.value + 1);

        // Add the new section to the PE struct
        self.sections.push(new_section);

        // Calculate and update the checksum
        let new_checksum = self.calc_checksum();
        self.header.checksum.update(&mut self.buffer, new_checksum);

        Ok(())
    }
```

**Comment by hackerbytermux** [comment]
thank you very much!

**Comment by hackerbytermux** [comment]
can you throw off the full code, please, if I just take the code from github and change the add section, I still have the same error

**Comment by hackerbytermux** [comment]
strangely, he found a collision, but there are no changes in the final file

**Comment by M3str3** [comment]
Hello again @hackerbytermux 😄 

It seems I misunderstood the situation. I did manage the collision correctly, but the bigger problem here is related to how the entry point is handled in your file.

I've noticed that the file you're testing doesn't have an **IMAGE_OPTIONAL_HEADER**, which is very unusual. Normally, the **Entry Point** is stored in that header, and without it, I’m not sure how the operating system knows where to start executing the code. This could explain why, even though no collision is detected and the changes are applied, the file still doesn’t work as expected.

![image](https://github.com/user-attachments/assets/5d3da6ad-c88d-4ec8-a994-5fc2aebedff9)

The issue is that HexSpell relies on the assumption that the **Entry Point** is stored in the **Optional Header**. In your case, since there is no **Optional Header**, modifying the Entry Point becomes strange, which means that after moving the **.text** section, the program cannot follow its usual execution flow. Additionally, it can't point to the new section to execute the code.

When you say "no changes in the final file," are you referring to the fact that your first section (**.text**) is still overwritten, or are you noticing something else? like the program doesnt run

If it's still being overwritten, that would be strange, especially if the code is working on other files. However, if the problem is that the file simply doesn't run after the changes, it likely comes down to the fact that we can't properly manage the Entry Point without the **Optional Header**.

Let me know what you're seeing on your end. I think we can dive deeper into this and figure it out together. Thanks again for your patience, and sorry for the confusion!

**Comment by hackerbytermux** [comment]
yes, the bug has been preserved, there is also an optional header in this file (I parsed it with my library), here is a screenshot from detect it easy

![image](https://github.com/user-attachments/assets/20ca21f4-8aae-4fda-89af-0bc43fbb8ba8)

**Comment by hackerbytermux** [comment]
when you try to add a section to a file compiled by rastom, it gives this
![image](https://github.com/user-attachments/assets/92520836-0ee1-44ad-bc49-8614cd33cd91)

**Comment by M3str3** [comment]
> yes, the bug has been preserved, there is also an optional header in this file (I parsed it with my library), here is a screenshot from detect it easy

ufffff, well I'll keep researching

> I think maybe the problem is that we are parsing the nt header with a static e_lfanew, in my library I took it from dos header

About this, I'm not clear on what you mean, sorry, hahaha. I mean I pick up the beginning of the header from the value found in 0x3C (DOS HEADER), how do you do it in your library? Would you know how to change it?

> when you try to add a section to a file compiled by rastom, it gives this

Yeah thats the overflow on calc_checksum it is fixed on branch 0.0.3 not already published (#5)

**Comment by hackerbytermux** [comment]
and yes, I didn't notice for sure, in my library I just use the structure of headers and mem::transmute (unsafe but works)
![image](https://github.com/user-attachments/assets/a094edc9-06c1-4e2a-baaa-1648ab3abe2c)
for pathing values i use:
![image](https://github.com/user-attachments/assets/f20757e2-0e8a-49c4-af16-a46b1cee803e)

**Comment by M3str3** [comment]
Hello again @hackerbytermux ,

Thanks for your patience and for providing me with the code, I see that other methods are possible and I will rethink some things and how I am doing them. Well, let's go with the problem, you were always right to tell me about the OPTIONAL_HEADER but the program I was using to display it was failing and that confused me..... 

# The Problem:
As for the problem is that in that same binary the sizeofheaders has a value of 0x200 and the headers occupy 100% of the space, so to insert a new header you have to increase the space of the same aligning it with the file_alignament, this is already being managed in the code that I show below.

I have done the tests with your binary and I am able to insert the shellcode and execute it.

# The Fix:

- **SizeOfHeaders Check**: Before adding a new section, I now check whether the section header fits within the SizeOfHeaders. If it doesn’t, I calculate the new SizeOfHeaders and align it properly based on the FileAlignment.
- **Buffer Adjustment**: If the SizeOfHeaders increases, I resize the buffer accordingly and adjust all section headers and PointerToRawData values to reflect the new layout.
- **Aligned Expansion**: The buffer now gets expanded with padding if necessary to prevent any overlap or misalignment issues, and all subsequent sections are moved forward to accommodate the changes.

## pe/mod:add_section()

```rust
    /// Adds a section to the PE file.
    ///
    /// # Arguments
    /// * `new_section` - The new section header to be added.
    /// * `shellcode` - The shellcode or data to be added in the new section.
    ///
    /// # Returns
    /// A `Result` indicating success or failure of the operation.
    pub fn add_section(
        &mut self,
        new_section: section::PeSection,
        shellcode: Vec<u8>,
    ) -> Result<(), FileParseError> {
        const SECTION_HEADER_SIZE: usize = 40;

        // Ensure the new section fits within the current SizeOfHeaders
        if new_section.characteristics.offset + new_section.characteristics.size
            > self.header.size_of_headers.value as usize
        {
            // Calculate new SizeOfHeaders based on the number of sections
            let new_size_of_headers =
                self.header.size_of_headers.value + SECTION_HEADER_SIZE as u32;

            // Align the new SizeOfHeaders according to the File Alignment
            let alig_new_size_of_headers = (new_size_of_headers + self.header.file_alignment.value
                - 1)
                & !(self.header.file_alignment.value - 1);
            let alig_old_size_of_headers = self.header.size_of_headers.value;

            if alig_new_size_of_headers != alig_old_size_of_headers {
                // Update the SizeOfHeaders in the PE header
                self.header
                    .size_of_headers
                    .update(&mut self.buffer, alig_new_size_of_headers);

                let diff = alig_new_size_of_headers as usize - alig_old_size_of_headers as usize;

                // Only insert padding if the diff is greater than 0
                if diff > 0 {
                    self.buffer.splice(
                        alig_old_size_of_headers as usize..alig_old_size_of_headers as usize,
                        std::iter::repeat(0).take(diff),
                    );

                    // Move the pointer_to_raw_data for each section based on the new SizeOfHeaders
                    for section in self.sections.iter_mut() {
                        section.pointer_to_raw_data.update(
                            &mut self.buffer,
                            section.pointer_to_raw_data.value + diff as u32,
                        );
                    }
                }
            }
        }

        // Calculate the total buffer size with the new section
        let raw_data_ptr = new_section.pointer_to_raw_data.value;
        let new_total_buffer_size =
            raw_data_ptr as usize + new_section.size_of_raw_data.value as usize;
        if self.buffer.len() < new_total_buffer_size {
            self.buffer.resize(new_total_buffer_size, 0);
        }

        // Insert the new section header into the buffer
        let mut section_header_buffer = Vec::with_capacity(SECTION_HEADER_SIZE);
        section_header_buffer.extend_from_slice(&new_section.name.value.as_bytes()[..8]);
        section_header_buffer.extend(&new_section.virtual_size.value.to_le_bytes());
        section_header_buffer.extend(&new_section.virtual_address.value.to_le_bytes());
        section_header_buffer.extend(&new_section.size_of_raw_data.value.to_le_bytes());
        section_header_buffer.extend(&new_section.pointer_to_raw_data.value.to_le_bytes());
        section_header_buffer.extend(&new_section.pointer_to_relocations.value.to_le_bytes());
        section_header_buffer.extend(&new_section.pointer_to_linenumbers.value.to_le_bytes());
        section_header_buffer.extend(&new_section.number_of_relocations.value.to_le_bytes());
        section_header_buffer.extend(&new_section.number_of_linenumbers.value.to_le_bytes());
        section_header_buffer.extend(&new_section.characteristics.value.to_le_bytes());

        self.buffer.splice(
            new_section.name.offset..new_section.name.offset + SECTION_HEADER_SIZE,
            section_header_buffer.iter().copied(),
        );

        // Insert the shellcode into the new section
        self.buffer.splice(
            raw_data_ptr as usize..raw_data_ptr as usize + shellcode.len(),
            shellcode.iter().copied(),
        );

        // Update the SizeOfImage aligned to Section Alignment
        let new_size_of_image = (new_section.virtual_address.value
            + new_section.virtual_size.value
            + self.header.section_alignment.value
            - 1)
            & !(self.header.section_alignment.value - 1);
        self.header
            .size_of_image
            .update(&mut self.buffer, new_size_of_image);

        // Update the number of sections in the header
        self.header
            .number_of_sections
            .update(&mut self.buffer, self.header.number_of_sections.value + 1);

        // Add the new section to the PE structure
        self.sections.push(new_section);

        // Recalculate and update the checksum
        let new_checksum = self.calc_checksum();
        self.header.checksum.update(&mut self.buffer, new_checksum);

        Ok(())
    }
```

## The test

```rust
fn test() {

    // msfvenom -p windows/x64/exec CMD="cmd.exe /c echo Hello, I'm in your code" -f rust --platform windows
    let shellcode = [
        0xfc, 0x48, 0x83, 0xe4, 0xf0, 0xe8, 0xc0, 0x00, 0x00, 0x00, 0x41, 0x51, 0x41, 0x50, 0x52,
        0x51, 0x56, 0x48, 0x31, 0xd2, 0x65, 0x48, 0x8b, 0x52, 0x60, 0x48, 0x8b, 0x52, 0x18, 0x48,
        0x8b, 0x52, 0x20, 0x48, 0x8b, 0x72, 0x50, 0x48, 0x0f, 0xb7, 0x4a, 0x4a, 0x4d, 0x31, 0xc9,
        0x48, 0x31, 0xc0, 0xac, 0x3c, 0x61, 0x7c, 0x02, 0x2c, 0x20, 0x41, 0xc1, 0xc9, 0x0d, 0x41,
        0x01, 0xc1, 0xe2, 0xed, 0x52, 0x41, 0x51, 0x48, 0x8b, 0x52, 0x20, 0x8b, 0x42, 0x3c, 0x48,
        0x01, 0xd0, 0x8b, 0x80, 0x88, 0x00, 0x00, 0x00, 0x48, 0x85, 0xc0, 0x74, 0x67, 0x48, 0x01,
        0xd0, 0x50, 0x8b, 0x48, 0x18, 0x44, 0x8b, 0x40, 0x20, 0x49, 0x01, 0xd0, 0xe3, 0x56, 0x48,
        0xff, 0xc9, 0x41, 0x8b, 0x34, 0x88, 0x48, 0x01, 0xd6, 0x4d, 0x31, 0xc9, 0x48, 0x31, 0xc0,
        0xac, 0x41, 0xc1, 0xc9, 0x0d, 0x41, 0x01, 0xc1, 0x38, 0xe0, 0x75, 0xf1, 0x4c, 0x03, 0x4c,
        0x24, 0x08, 0x45, 0x39, 0xd1, 0x75, 0xd8, 0x58, 0x44, 0x8b, 0x40, 0x24, 0x49, 0x01, 0xd0,
        0x66, 0x41, 0x8b, 0x0c, 0x48, 0x44, 0x8b, 0x40, 0x1c, 0x49, 0x01, 0xd0, 0x41, 0x8b, 0x04,
        0x88, 0x48, 0x01, 0xd0, 0x41, 0x58, 0x41, 0x58, 0x5e, 0x59, 0x5a, 0x41, 0x58, 0x41, 0x59,
        0x41, 0x5a, 0x48, 0x83, 0xec, 0x20, 0x41, 0x52, 0xff, 0xe0, 0x58, 0x41, 0x59, 0x5a, 0x48,
        0x8b, 0x12, 0xe9, 0x57, 0xff, 0xff, 0xff, 0x5d, 0x48, 0xba, 0x01, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x48, 0x8d, 0x8d, 0x01, 0x01, 0x00, 0x00, 0x41, 0xba, 0x31, 0x8b, 0x6f,
        0x87, 0xff, 0xd5, 0xbb, 0xf0, 0xb5, 0xa2, 0x56, 0x41, 0xba, 0xa6, 0x95, 0xbd, 0x9d, 0xff,
        0xd5, 0x48, 0x83, 0xc4, 0x28, 0x3c, 0x06, 0x7c, 0x0a, 0x80, 0xfb, 0xe0, 0x75, 0x05, 0xbb,
        0x47, 0x13, 0x72, 0x6f, 0x6a, 0x00, 0x59, 0x41, 0x89, 0xda, 0xff, 0xd5, 0x63, 0x6d, 0x64,
        0x2e, 0x65, 0x78, 0x65, 0x20, 0x2f, 0x63, 0x20, 0x65, 0x63, 0x68, 0x6f, 0x20, 0x48, 0x65,
        0x6c, 0x6c, 0x6f, 0x2c, 0x20, 0x49, 0x27, 0x6d, 0x20, 0x69, 0x6e, 0x20, 0x79, 0x6f, 0x75,
        0x72, 0x20, 0x63, 0x6f, 0x64, 0x65, 0x00,
    ]
    .to_vec();

    // Open PE from w
    let mut pe = PE::from_file("main.exe").expect("[!] Error opening PE file");

    let image_base = &pe.header.image_base.value;
    let offset = pe.sections[0].virtual_address.value as u64 + 0x34;
    let mut entry = 0;

    match image_base {
        ImageBase::Base32(_) => panic!("[!] Invalid image base"),
        ImageBase::Base64(addr) => entry = *addr,
    };

    entry = entry + offset;

    // Create new section header based on basic parameters
    let new_section_header = pe
        .generate_section_header(
            ".shell",               // Name for the new section
            shellcode.len() as u32, // The size of the data it has to store
            section::Characteristics::Code.to_u32() // Basic characteristics for a shellcode
            + section::Characteristics::Readable.to_u32()
            + section::Characteristics::Executable.to_u32(),
        )
        .expect("[!] Error generating new section header");

    // Add new section header and payload into PE
    pe.add_section(new_section_header, shellcode)
        .expect("[!] Error adding new section into PE");

    pe.write_file("out_no_entry.exe")
        .expect("[!] Error writing new PE to disk");

    // Optional: Update entry point to execute our payload instead of the original code
    pe.header.entry_point.update(&mut pe.buffer,pe.sections.last().unwrap().virtual_address.value);


    pe.write_file("out_w_entry.exe")
    .expect("[!] Error writing new PE to disk");
}
```


![Pasted image 20240921215342](https://github.com/user-attachments/assets/86eab51b-6fae-46ed-92be-110f833b1152)




# Final note
I also want to take a moment to sincerely thank you for your time and patience throughout this process. Your detailed feedback has been incredibly valuable, and I really appreciate you using HexSpell and helping to improve it. Your input has made a real difference!

**Comment by M3str3** [comment]
I will continue with my main idea, tomorrow I will upload this patch to 0.0.3 and around monday I will publish it with the corrections.

**Comment by hackerbytermux** [comment]
Very cool, thanks!
